name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: Update apt-get
      run: sudo apt-get update
    - name: Install deps
      run: sudo apt-get install -y coreutils quilt parted kpartx qemu-utils qemu-user-static debootstrap zerofree zip dosfstools libarchive-tools libcap2-bin grep rsync xz-utils file git curl bc
    - run: mkdir .ccache
    - name: Set up ccache cache
      uses: actions/cache@v4
      with:
        path: .ccache
        key: ccache-${{ github.run_number }}
        restore-keys: |
          ccache
    - name: Build
      run: sudo ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: images-qemu
        path: deploy/*.zip
